version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  chatops-bot:
    lang: golang-middleware
    handler: ./chatops-bot
    image: hello-world:latest
  certinfo:
    lang: dockerfile
    handler: ./certinfo
    image: certinfo:armhf
  figlet:
    lang: dockerfile
    handler: ./figlet
    image: figlet:latest
  hello-python:
    lang: python3
    handler: ./hello-python
    image: hello-python:latest

