version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  chatops-bot:
    lang: golang-middleware
    handler: ./chatops-bot
    image: hello-world:latest
  certinfo:
    lang: dockerfile
    handler: ./certinfo
    image: certinfo:armhf
  figlet:
    lang: dockerfile
    handler: ./figlet
    image: figlet:latest
  route53:
    lang: golang-middleware
    handler: ./route53
    image: route53:latest
#    secrets:
#      - r53

#  images:
#    lang: golang-middleware
#    handler: ./images
#    image: images:latest
#    secrets:
#      - s3
#    environment:
#      s3_tls: false
#      s3_url: minio.openfaas.svc.cluster.local:9000
