version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  chatops-bot:
    lang: golang-middleware
    handler: ./chatops-bot
    image: hello-world:latest
    # faas-cli cloud seal --name waterdrips-super-secret --literal super-secret=super-secret-information -c pub-cert.pem
    # secrets:
      # - super-secret
  certinfo:
    lang: dockerfile
    handler: ./certinfo
    image: certinfo:armhf
  figlet:
    lang: dockerfile
    handler: ./figlet
    image: figlet:latest
  route53:
    lang: golang-middleware
    handler: ./route53
    image: route53:latest
    environment:
      content-type: application/json
    secrets:
      - r53

