version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hello-world:
    lang: golang-middleware
    handler: ./hello-world
    image: hello-world:latest
  certinfo:
    lang: dockerfile
    handler: ./certinfo
    image: certinfo:armhf
  figlet:
    lang: dockerfile
    handler: ./figlet
    image: figlet:latest
